# Generated by Django 4.1.4 on 2022-12-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='0000000', max_length=254),
        ),
        migrations.AddField(
            model_name='students',
            name='student_number',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(default='0000000', max_length=254),
        ),
        migrations.AddField(
            model_name='teachers',
            name='username',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(default='0000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='first_name',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
