# Generated by Django 4.1.4 on 2023-01-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_students_email_students_student_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_number',
            new_name='username',
        ),
    ]
