# Generated by Django 4.1.4 on 2023-01-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_student_number_students_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='homework',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='sessions',
            name='note',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='sessions',
            name='voice',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='student_classes',
            name='accessibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(default='Class Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='Enter Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(default='Enter First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(default='Enter Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(default='Enter Username', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(default='Enter Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='first_name',
            field=models.CharField(default='Enter First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(default='Enter Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='username',
            field=models.CharField(default='Enter Username', max_length=100),
        ),
    ]
